name: main
on: [pull_request, push]
jobs:
  pre-process:
     name: pre-process
     runs-on: ubuntu-latest
     outputs:
       were-only-docs-updated: ${{ steps.were-only-docs-updated-action.outputs.were-only-docs-updated }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
         with: 
           fetch-depth: 2. 
       - name: Get commit range
         id: get-commit-range-action
         uses: ./.github/actions/get-commit-range-action
       - name: Were only docs updated
         id: were-only-docs-updated-action
         uses: ./.github/actions/were-only-docs-updated-action
         with: 
           commit-range: ${{ steps.get-commit-range-action.outputs.commit-range }}
  check-header:
     name: Check Header
     runs-on: ubuntu-latest
     needs: pre-process
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
         with: 
           fetch-depth: 2.
       - name: Get commit range
         id: get-commit-range-action
         uses: ./.github/actions/get-commit-range-action
       - name: Check header
         run: |
           git clone --branch=devops https://github.com/vmware/singleton.git devops
           cp $TRAVIS_BUILD_DIR/devops/check_headers.py .
           chmod +x check_headers.py
           python3 ./check_headers.py -f "$(git diff --name-only --diff-filter=d $TRAVIS_COMMIT_RANGE)"
  unit-test:
     name: Unit Test
     runs-on: ubuntu-latest
     needs: pre-process
     steps: 
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Set up JDK 8
         uses: actions/setup-java@v2
         with: 
            distribution: 'adopt'
            java-version: '8'
       - name: Unit test
         run: |
            cd $TRAVIS_BUILD_DIR/devops/sonar
           ./gradlew test jacocoTestReport

