name: main
on: [pull_request, push]
jobs:
  pre-process:
    name: Pre process
    runs-on: ubuntu-latest
    outputs:
      were-only-docs-updated: ${{ steps.were-only-docs-updated-action.outputs.were-only-docs-updated }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2.  
      - name: Get commit range
        id: get-commit-range-action
        uses: ./.github/actions/get-commit-range-action
      - name: Were only docs updated
        id: were-only-docs-updated-action
        uses: ./.github/actions/were-only-docs-updated-action
        with:
          commit-range: ${{ steps.get-commit-range-action.outputs.commit-range }}
  check-header:
    name: Check Header
    runs-on: ubuntu-latest
    needs: pre-process
    if: needs.pre-process.outputs.were-only-docs-updated != 'yes'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2.  
      - name: Get commit range
        id: get-commit-range-action
        uses: ./.github/actions/get-commit-range-action
      - name: Check header
        run: |
          git clone --branch=devops https://github.com/vmware/singleton.git devops
          cp $GITHUB_WORKSPACE/devops/check_headers.py .
          chmod +x check_headers.py
          git diff ${{ steps.get-commit-range-action.outputs.commit-range }} --stat
          git diff --name-only --diff-filter=d ${{ steps.get-commit-range-action.outputs.commit-range }}
          python ./check_headers.py -f "$(git diff --name-only --diff-filter=d ${{ steps.get-commit-range-action.outputs.commit-range }})"
  unit-test:
      runs-on: ubuntu-latest
      needs: pre-process
      if: needs.pre-process.outputs.were-only-docs-updated != 'yes'
      strategy: 
        matrix:
          python-version: [ '2.7', '3.5', '3.7' ]
      name: Python ${{ matrix.python-version }} sample
      steps: 
        - name: checkout code
          uses: actions/checkout@v2
        - name: Set up JDK 2.7 3.5 3.7
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
            architecture: x64
        - name: Unit test
          run: |
            cd sgtn4python/test
            pip install requests coverage pyyaml
            str=$(printf '=%.0s' {1..50})
            echo $str Unit Test Start $str
            python -m unittest discover
            echo $str Unit Test End $str
            coverage run --source='.' test_sgtn_client.py
             

 
            
            
            
         
  
            
